# Generated by Django 4.2.3 on 2023-07-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('uy', 'Uy'), ('dom', 'Dom'), ('kvartira', 'Kvartira'), ('bezniz', 'Bezniz uchun')], max_length=20)),
                ('joy', models.CharField(max_length=100)),
                ('kv_soni', models.IntegerField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('describe', models.TextField()),
                ('rasm1', models.ImageField(upload_to='rasm')),
                ('rasm2', models.ImageField(upload_to='rasm')),
                ('rasm3', models.ImageField(upload_to='rasm')),
                ('rasm4', models.ImageField(upload_to='rasm')),
                ('rasm5', models.ImageField(upload_to='rasm')),
                ('rasm6', models.ImageField(upload_to='rasm')),
            ],
        ),
    ]
